const raw = [
    "password",
    "passwd",
    "pwd",
    "passcode",
    "secret",
    "secretkey",
    "privatekey",
    "apikey",
    "api_key",
    "accesskey",
    "access_key",
    "token",
    "authtoken",
    "auth_token",
    "refreshtoken",
    "refresh_token",
    "authorization",
    "authorizationheader",
    "authheader",
    "bearer",
    "session",
    "sessionid",
    "session_id",
    "sid",
    "jsessionid",
    "cookie",
    "setcookie",
    "set_cookie",
    "csrf",
    "xsrf",
    "credential",
    "credentials",
    "login",
    "username",
    "user",
    "email",
    "e-mail",
    "phone",
    "phonenumber",
    "mobile",
    "msisdn",
    "nik",
    "ktp",
    "npwp",
    "ssn",
    "socialsecurity",
    "identity",
    "identitynumber",
    "idnumber",
    "payment",
    "card",
    "cardnumber",
    "cc",
    "creditcard",
    "debitcard",
    "cvv",
    "cvc",
    "expiry",
    "expdate",
    "iban",
    "swift",
    "bic",
    "bank",
    "account",
    "accountnumber",
    "routing",
    "pin",
    "otp",
    "one_time_password",
    "mfa",
    "totp",
    "private",
    "confidential",
    "secure",
    "vault",
    "key",
    "signature",
    "sign",
    "hash",
    "salt",
    "seed",
    "mnemonic",
    "recovery",
    "backupcode"
]

const normalize = v => v.toLowerCase().replace(/[^a-z0-9]/g, "")

const expanded = raw
    .map(normalize)
    .reduce((acc, v) => {
        acc.add(v)
        if (v.endsWith("id")) acc.add(v.slice(0, -2))
        if (v.startsWith("auth")) acc.add(v.replace("auth", ""))
        if (v.endsWith("token")) acc.add(v.replace("token", ""))
        return acc
    }, new Set())

export default expanded
